name = "ok-academy-nextjs"
compatibility_date = "2026-03-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "db-perfect-link"
database_id = "8f524f1a-bba3-424a-92f4-4d24d716ff23"
